### ISSUE TITLE
Similar Project

### ISSUE THREAD

**Issue by ebsuku** [buza-project/buza-website#25]
Hi folks
This seems like are very interesting project and I'd very much like to help out if possible.

There is another project called [scoold](https://scoold.com/) which attempts to be an open source Q&A platform. you might be able to get some ideas off it.

**Comment by pjdelport** [comment]
Thanks @ebsuku! :)

That definitely looks relevant, yeah: I'll check it out.

I just started a GitHub team for us to host discussions: do you mind if we capture and move this discussion there?

Discussion:

* [Similar project: Scoold (Java-based StackOverflow-alike)](https://github.com/orgs/buza-project/teams/contributors/discussions/1)
